[project]
name = "elacticsearch-demo"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=2.3.1,<3.0.0)",
    "sentence-transformers (>=5.0.0,<6.0.0)",
    "elasticsearch (>=9.0.2,<10.0.0)",
    "chardet (>=5.2.0,<6.0.0)",
    "datasets (>=4.0.0,<5.0.0)",
    "matplotlib (>=3.10.3,<4.0.0)"
]

[tool.poetry]
packages = [{include = "elacticsearch_demo", from = "src"}]

[tool.poetry.scripts]
vector-search = "elasticsearch_demo.vector_search:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
